############################################
#                GENERAL                   #
############################################

server.port: 9999

############################################
#                UNDERTOW                  #
############################################
server:
  max-http-header-size: 16KB
  servlet:
    context-path: /api
    session:
      timeout: 120s
  undertow:
    accesslog:
      dir: logs/access
      enabled: true


